### ISSUE TITLE
GermlineCNVCaller resource consumption

### ISSUE THREAD

**Issue by HudoGriz** [nf-core/createpanelrefs#32]
### Description of the bug

Hi,
I noticed that `GermlineCNVCaller` called in the `GATK4_GERMLINECNVCALLER` job eats up all available threads on a node. I made a quick fix by exporting `MKL_NUM_THREADS` & `OMP_NUM_THREADS` vars.

Kind regards,

Blaž

**Comment by ramprasadn** [comment]
Good catch @HudoGriz. I will make the changes in the modules repo and then update them in the pipeline.
